paths:
  srcdir: C:\Users\maria\Desktop\Articulos_version_Sept\Breast_Cancer\Data\Breast_Cancer
  datadir: C:\Users\maria\Desktop\Articulos_version_Sept\Breast_Cancer\Data\model_data
  model: dnn.pt
  scaler: dnn_scaler.pt

data:
  splits:
    train: 0.7
    valid: 0.2
    test: 0.1

scaler: std

loaders:
  batch_size: 64

optimizer:
  lr: [1e-4, 5e-4, 1e-3, 5e-3]
  weight_decay: 0.005
  betas: [0.9, 0.999]

model:
  type: DNN

  input_size: 8
  output_size: 1

  hidden_sizes: [[64, 32, 16], [128, 64, 32], [256, 128, 64], [128, 128], [256, 128], [512, 256, 128]]

  batch_size: [32, 64, 128]

  activation: relu
  use_layer_norm: false
  bias: true

fit:
  num_epochs: 100
  patience: 10
  min_delta: 0.05